-- 0004 — reference data.
--
-- Generated by scripts/build-reference-migration.ts from the same
-- catalogues the interface reads, so the two cannot drift. Re-run the
-- script rather than editing this file by hand.
--
-- Nothing here names a person. This is the only data production starts
-- with; every other row must be created by a real user through the real
-- application.

PRAGMA foreign_keys = ON;

-- --- Exercise catalogue --------------------------------------------------

INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_jumping_jacks', 'Jumping Jacks', '["full body"]', 'bodyweight', 8, 'Land soft, stay light on your feet.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_high_knees', 'High Knees', '["legs","core"]', 'bodyweight', 8, 'Drive the knee to hip height.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_butt_kicks', 'Butt Kicks', '["legs"]', 'bodyweight', 7, 'Quick feet, tall chest.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_skater_hops', 'Skater Hops', '["legs","glutes"]', 'bodyweight', 7, 'Push out sideways, land balanced.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_burpee', 'Burpees', '["full body"]', 'bodyweight', 10, 'Pace yourself — smooth beats fast.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_mountain_climbers', 'Mountain Climbers', '["core","shoulders"]', 'bodyweight', 8, 'Hips stay level, no bouncing.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_squat', 'Bodyweight Squats', '["quads","glutes"]', 'bodyweight', 5.5, 'Sit back, knees track over toes.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_sumo_squat', 'Sumo Squats', '["glutes","inner thigh"]', 'bodyweight', 5.5, 'Wide stance, toes turned out.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_reverse_lunge', 'Reverse Lunges', '["quads","glutes"]', 'bodyweight', 6, 'Step back, drop straight down.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_step_up', 'Step-ups', '["quads","glutes"]', 'bodyweight', 6, 'Drive through the front heel.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_wall_sit', 'Wall Sit', '["quads"]', 'bodyweight', 4.5, 'Thighs parallel, breathe through it.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_calf_raise', 'Calf Raises', '["calves"]', 'bodyweight', 3.5, 'Full range, pause at the top.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_glute_bridge', 'Glute Bridge', '["glutes","hamstrings"]', 'bodyweight', 4, 'Squeeze at the top, ribs down.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_donkey_kick', 'Donkey Kicks', '["glutes"]', 'bodyweight', 3.5, 'Move from the hip, not the back.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_push_up', 'Push-ups', '["chest","triceps"]', 'bodyweight', 8, 'Knees down is a real push-up too.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_superman', 'Superman Hold', '["lower back"]', 'bodyweight', 3.5, 'Lift long, not high.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_plank', 'Plank', '["core"]', 'bodyweight', 3.8, 'Straight line from head to heels.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_side_plank', 'Side Plank', '["obliques"]', 'bodyweight', 3.8, 'Stack the shoulders, lift the hips.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_crunch', 'Crunches', '["abs"]', 'bodyweight', 3.8, 'Chin off the chest, curl the ribs.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_bicycle_crunch', 'Bicycle Crunches', '["abs","obliques"]', 'bodyweight', 6, 'Slow and controlled beats fast.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_leg_raise', 'Leg Raises', '["lower abs"]', 'bodyweight', 4, 'Press the lower back into the floor.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_russian_twist', 'Russian Twists', '["obliques"]', 'bodyweight', 4.5, 'Rotate through the ribs.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_flutter_kick', 'Flutter Kicks', '["lower abs"]', 'bodyweight', 4.5, 'Small kicks, steady breathing.');
INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES ('ex_dead_bug', 'Dead Bug', '["core"]', 'bodyweight', 3.5, 'Ribs down the whole time.');

-- --- Achievement definitions ---------------------------------------------

INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('first_workout', 'First Workout', 'You started. That is the hard part.', '🌱', 'training', 'Complete one workout.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('five_workouts', '5 Workouts', 'Five done. It is starting to stick.', '🔩', 'training', 'Complete 5 workouts.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('ten_workouts', '10 Workouts', 'Ten sessions in the bank.', '🏋️', 'training', 'Complete 10 workouts.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('twentyfive_workouts', '25 Workouts', 'Twenty-five. That is a real base.', '🧱', 'training', 'Complete 25 workouts.', 4);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('fifty_workouts', '50 Workouts', 'This is a habit now, not a phase.', '🥇', 'training', 'Complete 50 workouts.', 5);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('hundred_workouts', '100 Workouts', 'One hundred times you chose to go.', '💯', 'training', 'Complete 100 workouts.', 6);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_3', '3 Day Streak', 'Three in a row. The chain has started.', '✨', 'streak', 'Log something on 3 days in a row.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_7', '7 Day Streak', 'A full week without breaking the chain.', '🔥', 'streak', 'Log something on 7 days in a row.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_14', '14 Day Streak', 'Two weeks straight.', '🌟', 'streak', 'Log something on 14 days in a row.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_30', '30 Day Streak', 'A month of showing up.', '⚡', 'streak', 'Log something on 30 days in a row.', 4);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_60', '60 Day Streak', 'Two months unbroken.', '☄️', 'streak', 'Log something on 60 days in a row.', 5);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('streak_90', '90 Day Streak', 'Ninety days. This is just who you are now.', '👑', 'streak', 'Log something on 90 days in a row.', 6);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('steps_10k_day', '10,000 Steps', 'Ten thousand steps in a single day.', '🚶', 'steps', 'Record 10,000 steps in a single day.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('steps_50k', '50,000 Steps', 'Fifty thousand steps logged.', '👟', 'steps', 'Record 50,000 steps in total.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('steps_100k', '100,000 Steps', 'Six figures on foot.', '🥾', 'steps', 'Record 100,000 steps in total.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('steps_500k', '500,000 Steps', 'Half a million. That is a long way.', '🗺️', 'steps', 'Record 500,000 steps in total.', 4);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('steps_1m', '1 Million Steps', 'A million steps. Genuinely remarkable.', '🌍', 'steps', 'Record 1,000,000 steps in total.', 5);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('first_kg', 'First 1 kg', 'The first one proves it works.', '⚖️', 'body', 'Move 1 kg toward your own target, whichever direction that is.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('three_kg', '3 kg Progress', 'Three kilograms in the right direction.', '📐', 'body', 'Move 3 kg toward your own target.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('five_kg', '5 kg Progress', 'Five kilograms of real change.', '🎯', 'body', 'Move 5 kg toward your own target.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('ten_kg', '10 kg Progress', 'Ten kilograms. People will have noticed.', '🏔️', 'body', 'Move 10 kg toward your own target.', 4);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('goal_reached', 'Goal Reached', 'You said you would, and you did.', '🏁', 'body', 'Reach your target weight.', 5);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('nutrition_7', '7 Days Logged', 'A week of knowing what you ate.', '🍎', 'nutrition', 'Log food on 7 separate days.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('nutrition_14', '14 Days Logged', 'Two weeks of paying attention.', '🥗', 'nutrition', 'Log food on 14 separate days.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('nutrition_30', '30 Days Logged', 'A month logged. That takes patience.', '📗', 'nutrition', 'Log food on 30 separate days.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('consistency_7', '7 Day Consistency', 'Seven active days recorded.', '📅', 'consistency', 'Have 7 days on which you logged a workout, steps or a weigh-in.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('consistency_30', '30 Day Consistency', 'Steady for a whole month.', '📈', 'consistency', 'Have 30 such days.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('consistency_60', '60 Day Consistency', 'Sixty active days. Quietly impressive.', '🧭', 'consistency', 'Have 60 such days.', 3);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('first_weigh_in', 'First Weekly Weigh-in', 'Your progress story has a beginning.', '📌', 'special', 'Record one weekly weigh-in.', 1);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('first_update', 'First Group Update', 'You told the others. That is the whole point.', '📣', 'special', 'Post one update to the group.', 2);
INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES ('first_pr', 'First Personal Best', 'Your best session yet.', '💥', 'special', 'Record a set that beats your previous best for that exercise.', 3);
