-- The plan catalogue.
--
-- Generated by scripts/build-plan-migration.ts from src/data/library.ts, so
-- the programmes on the server are the same programmes the application builds
-- rather than a transcription of them. Regenerate rather than edit.
--
-- Reference data: exercise templates and the days they fall on. It names
-- nobody, owns nothing, and records no progress. `owner_id` is null on every
-- row because these belong to the app, not to a person.
--
-- Safe to apply to an empty production database.


INSERT INTO plans (id, owner_id, name, description, total_days, level, focus, created_at)
VALUES ('plan_lose_weight_30', NULL, 'Lose Weight 30 Days Plan', 'Short, repeatable sessions six days out of seven. Built to be done in a living room before work.', 30, 'beginner', '["Fat loss","Full body","No equipment"]', '2026-01-01T00:00:00.000Z')
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d1', 'plan_lose_weight_30', 1, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e0', 'plan_lose_weight_30_d1', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e1', 'plan_lose_weight_30_d1', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e2', 'plan_lose_weight_30_d1', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e3', 'plan_lose_weight_30_d1', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e4', 'plan_lose_weight_30_d1', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e5', 'plan_lose_weight_30_d1', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e6', 'plan_lose_weight_30_d1', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d1_e7', 'plan_lose_weight_30_d1', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d2', 'plan_lose_weight_30', 2, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e0', 'plan_lose_weight_30_d2', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e1', 'plan_lose_weight_30_d2', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e2', 'plan_lose_weight_30_d2', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e3', 'plan_lose_weight_30_d2', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e4', 'plan_lose_weight_30_d2', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e5', 'plan_lose_weight_30_d2', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e6', 'plan_lose_weight_30_d2', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d2_e7', 'plan_lose_weight_30_d2', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d3', 'plan_lose_weight_30', 3, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e0', 'plan_lose_weight_30_d3', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e1', 'plan_lose_weight_30_d3', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e2', 'plan_lose_weight_30_d3', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e3', 'plan_lose_weight_30_d3', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e4', 'plan_lose_weight_30_d3', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e5', 'plan_lose_weight_30_d3', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e6', 'plan_lose_weight_30_d3', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d3_e7', 'plan_lose_weight_30_d3', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d4', 'plan_lose_weight_30', 4, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e0', 'plan_lose_weight_30_d4', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e1', 'plan_lose_weight_30_d4', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e2', 'plan_lose_weight_30_d4', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e3', 'plan_lose_weight_30_d4', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e4', 'plan_lose_weight_30_d4', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e5', 'plan_lose_weight_30_d4', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e6', 'plan_lose_weight_30_d4', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d4_e7', 'plan_lose_weight_30_d4', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d5', 'plan_lose_weight_30', 5, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e0', 'plan_lose_weight_30_d5', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e1', 'plan_lose_weight_30_d5', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e2', 'plan_lose_weight_30_d5', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e3', 'plan_lose_weight_30_d5', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e4', 'plan_lose_weight_30_d5', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e5', 'plan_lose_weight_30_d5', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e6', 'plan_lose_weight_30_d5', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d5_e7', 'plan_lose_weight_30_d5', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d6', 'plan_lose_weight_30', 6, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d7', 'plan_lose_weight_30', 7, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e0', 'plan_lose_weight_30_d7', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e1', 'plan_lose_weight_30_d7', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e2', 'plan_lose_weight_30_d7', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e3', 'plan_lose_weight_30_d7', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e4', 'plan_lose_weight_30_d7', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e5', 'plan_lose_weight_30_d7', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e6', 'plan_lose_weight_30_d7', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d7_e7', 'plan_lose_weight_30_d7', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d8', 'plan_lose_weight_30', 8, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e0', 'plan_lose_weight_30_d8', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e1', 'plan_lose_weight_30_d8', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e2', 'plan_lose_weight_30_d8', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e3', 'plan_lose_weight_30_d8', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e4', 'plan_lose_weight_30_d8', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e5', 'plan_lose_weight_30_d8', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e6', 'plan_lose_weight_30_d8', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d8_e7', 'plan_lose_weight_30_d8', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d9', 'plan_lose_weight_30', 9, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e0', 'plan_lose_weight_30_d9', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e1', 'plan_lose_weight_30_d9', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e2', 'plan_lose_weight_30_d9', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e3', 'plan_lose_weight_30_d9', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e4', 'plan_lose_weight_30_d9', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e5', 'plan_lose_weight_30_d9', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e6', 'plan_lose_weight_30_d9', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d9_e7', 'plan_lose_weight_30_d9', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d10', 'plan_lose_weight_30', 10, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e0', 'plan_lose_weight_30_d10', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e1', 'plan_lose_weight_30_d10', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e2', 'plan_lose_weight_30_d10', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e3', 'plan_lose_weight_30_d10', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e4', 'plan_lose_weight_30_d10', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e5', 'plan_lose_weight_30_d10', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e6', 'plan_lose_weight_30_d10', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d10_e7', 'plan_lose_weight_30_d10', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d11', 'plan_lose_weight_30', 11, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e0', 'plan_lose_weight_30_d11', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e1', 'plan_lose_weight_30_d11', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e2', 'plan_lose_weight_30_d11', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e3', 'plan_lose_weight_30_d11', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e4', 'plan_lose_weight_30_d11', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e5', 'plan_lose_weight_30_d11', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e6', 'plan_lose_weight_30_d11', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d11_e7', 'plan_lose_weight_30_d11', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d12', 'plan_lose_weight_30', 12, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d13', 'plan_lose_weight_30', 13, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e0', 'plan_lose_weight_30_d13', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e1', 'plan_lose_weight_30_d13', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e2', 'plan_lose_weight_30_d13', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e3', 'plan_lose_weight_30_d13', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e4', 'plan_lose_weight_30_d13', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e5', 'plan_lose_weight_30_d13', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e6', 'plan_lose_weight_30_d13', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d13_e7', 'plan_lose_weight_30_d13', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d14', 'plan_lose_weight_30', 14, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e0', 'plan_lose_weight_30_d14', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e1', 'plan_lose_weight_30_d14', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e2', 'plan_lose_weight_30_d14', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e3', 'plan_lose_weight_30_d14', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e4', 'plan_lose_weight_30_d14', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e5', 'plan_lose_weight_30_d14', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e6', 'plan_lose_weight_30_d14', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d14_e7', 'plan_lose_weight_30_d14', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d15', 'plan_lose_weight_30', 15, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e0', 'plan_lose_weight_30_d15', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e1', 'plan_lose_weight_30_d15', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e2', 'plan_lose_weight_30_d15', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e3', 'plan_lose_weight_30_d15', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e4', 'plan_lose_weight_30_d15', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e5', 'plan_lose_weight_30_d15', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e6', 'plan_lose_weight_30_d15', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d15_e7', 'plan_lose_weight_30_d15', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d16', 'plan_lose_weight_30', 16, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e0', 'plan_lose_weight_30_d16', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e1', 'plan_lose_weight_30_d16', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e2', 'plan_lose_weight_30_d16', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e3', 'plan_lose_weight_30_d16', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e4', 'plan_lose_weight_30_d16', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e5', 'plan_lose_weight_30_d16', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e6', 'plan_lose_weight_30_d16', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d16_e7', 'plan_lose_weight_30_d16', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d17', 'plan_lose_weight_30', 17, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e0', 'plan_lose_weight_30_d17', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e1', 'plan_lose_weight_30_d17', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e2', 'plan_lose_weight_30_d17', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e3', 'plan_lose_weight_30_d17', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e4', 'plan_lose_weight_30_d17', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e5', 'plan_lose_weight_30_d17', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e6', 'plan_lose_weight_30_d17', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d17_e7', 'plan_lose_weight_30_d17', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d18', 'plan_lose_weight_30', 18, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d19', 'plan_lose_weight_30', 19, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e0', 'plan_lose_weight_30_d19', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e1', 'plan_lose_weight_30_d19', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e2', 'plan_lose_weight_30_d19', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e3', 'plan_lose_weight_30_d19', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e4', 'plan_lose_weight_30_d19', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e5', 'plan_lose_weight_30_d19', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e6', 'plan_lose_weight_30_d19', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d19_e7', 'plan_lose_weight_30_d19', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d20', 'plan_lose_weight_30', 20, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e0', 'plan_lose_weight_30_d20', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e1', 'plan_lose_weight_30_d20', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e2', 'plan_lose_weight_30_d20', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e3', 'plan_lose_weight_30_d20', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e4', 'plan_lose_weight_30_d20', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e5', 'plan_lose_weight_30_d20', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e6', 'plan_lose_weight_30_d20', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d20_e7', 'plan_lose_weight_30_d20', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d21', 'plan_lose_weight_30', 21, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e0', 'plan_lose_weight_30_d21', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e1', 'plan_lose_weight_30_d21', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e2', 'plan_lose_weight_30_d21', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e3', 'plan_lose_weight_30_d21', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e4', 'plan_lose_weight_30_d21', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e5', 'plan_lose_weight_30_d21', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e6', 'plan_lose_weight_30_d21', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d21_e7', 'plan_lose_weight_30_d21', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d22', 'plan_lose_weight_30', 22, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e0', 'plan_lose_weight_30_d22', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e1', 'plan_lose_weight_30_d22', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e2', 'plan_lose_weight_30_d22', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e3', 'plan_lose_weight_30_d22', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e4', 'plan_lose_weight_30_d22', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e5', 'plan_lose_weight_30_d22', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e6', 'plan_lose_weight_30_d22', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d22_e7', 'plan_lose_weight_30_d22', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d23', 'plan_lose_weight_30', 23, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e0', 'plan_lose_weight_30_d23', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e1', 'plan_lose_weight_30_d23', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e2', 'plan_lose_weight_30_d23', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e3', 'plan_lose_weight_30_d23', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e4', 'plan_lose_weight_30_d23', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e5', 'plan_lose_weight_30_d23', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e6', 'plan_lose_weight_30_d23', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d23_e7', 'plan_lose_weight_30_d23', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d24', 'plan_lose_weight_30', 24, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d25', 'plan_lose_weight_30', 25, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e0', 'plan_lose_weight_30_d25', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e1', 'plan_lose_weight_30_d25', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e2', 'plan_lose_weight_30_d25', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e3', 'plan_lose_weight_30_d25', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e4', 'plan_lose_weight_30_d25', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e5', 'plan_lose_weight_30_d25', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e6', 'plan_lose_weight_30_d25', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d25_e7', 'plan_lose_weight_30_d25', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d26', 'plan_lose_weight_30', 26, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e0', 'plan_lose_weight_30_d26', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e1', 'plan_lose_weight_30_d26', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e2', 'plan_lose_weight_30_d26', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e3', 'plan_lose_weight_30_d26', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e4', 'plan_lose_weight_30_d26', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e5', 'plan_lose_weight_30_d26', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e6', 'plan_lose_weight_30_d26', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d26_e7', 'plan_lose_weight_30_d26', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d27', 'plan_lose_weight_30', 27, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e0', 'plan_lose_weight_30_d27', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e1', 'plan_lose_weight_30_d27', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e2', 'plan_lose_weight_30_d27', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e3', 'plan_lose_weight_30_d27', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e4', 'plan_lose_weight_30_d27', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e5', 'plan_lose_weight_30_d27', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e6', 'plan_lose_weight_30_d27', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d27_e7', 'plan_lose_weight_30_d27', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d28', 'plan_lose_weight_30', 28, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e0', 'plan_lose_weight_30_d28', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e1', 'plan_lose_weight_30_d28', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e2', 'plan_lose_weight_30_d28', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e3', 'plan_lose_weight_30_d28', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e4', 'plan_lose_weight_30_d28', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e5', 'plan_lose_weight_30_d28', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e6', 'plan_lose_weight_30_d28', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d28_e7', 'plan_lose_weight_30_d28', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d29', 'plan_lose_weight_30', 29, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e0', 'plan_lose_weight_30_d29', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e1', 'plan_lose_weight_30_d29', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e2', 'plan_lose_weight_30_d29', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e3', 'plan_lose_weight_30_d29', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e4', 'plan_lose_weight_30_d29', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e5', 'plan_lose_weight_30_d29', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e6', 'plan_lose_weight_30_d29', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_lose_weight_30_d29_e7', 'plan_lose_weight_30_d29', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_lose_weight_30_d30', 'plan_lose_weight_30', 30, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plans (id, owner_id, name, description, total_days, level, focus, created_at)
VALUES ('plan_full_body_beginner', NULL, 'Full Body Beginner', 'Four sessions a week with real rest between them. The one to pick if you are starting from zero.', 28, 'beginner', '["Getting started","Full body","Gentle"]', '2026-01-01T00:00:00.000Z')
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d1', 'plan_full_body_beginner', 1, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e0', 'plan_full_body_beginner_d1', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e1', 'plan_full_body_beginner_d1', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e2', 'plan_full_body_beginner_d1', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e3', 'plan_full_body_beginner_d1', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e4', 'plan_full_body_beginner_d1', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e5', 'plan_full_body_beginner_d1', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e6', 'plan_full_body_beginner_d1', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d1_e7', 'plan_full_body_beginner_d1', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d2', 'plan_full_body_beginner', 2, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d3', 'plan_full_body_beginner', 3, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e0', 'plan_full_body_beginner_d3', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e1', 'plan_full_body_beginner_d3', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e2', 'plan_full_body_beginner_d3', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e3', 'plan_full_body_beginner_d3', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e4', 'plan_full_body_beginner_d3', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e5', 'plan_full_body_beginner_d3', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e6', 'plan_full_body_beginner_d3', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d3_e7', 'plan_full_body_beginner_d3', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d4', 'plan_full_body_beginner', 4, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d5', 'plan_full_body_beginner', 5, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e0', 'plan_full_body_beginner_d5', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e1', 'plan_full_body_beginner_d5', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e2', 'plan_full_body_beginner_d5', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e3', 'plan_full_body_beginner_d5', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e4', 'plan_full_body_beginner_d5', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e5', 'plan_full_body_beginner_d5', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e6', 'plan_full_body_beginner_d5', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d5_e7', 'plan_full_body_beginner_d5', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d6', 'plan_full_body_beginner', 6, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d7', 'plan_full_body_beginner', 7, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e0', 'plan_full_body_beginner_d7', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e1', 'plan_full_body_beginner_d7', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e2', 'plan_full_body_beginner_d7', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e3', 'plan_full_body_beginner_d7', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e4', 'plan_full_body_beginner_d7', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e5', 'plan_full_body_beginner_d7', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e6', 'plan_full_body_beginner_d7', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d7_e7', 'plan_full_body_beginner_d7', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d8', 'plan_full_body_beginner', 8, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e0', 'plan_full_body_beginner_d8', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e1', 'plan_full_body_beginner_d8', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e2', 'plan_full_body_beginner_d8', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e3', 'plan_full_body_beginner_d8', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e4', 'plan_full_body_beginner_d8', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e5', 'plan_full_body_beginner_d8', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e6', 'plan_full_body_beginner_d8', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d8_e7', 'plan_full_body_beginner_d8', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d9', 'plan_full_body_beginner', 9, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d10', 'plan_full_body_beginner', 10, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e0', 'plan_full_body_beginner_d10', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e1', 'plan_full_body_beginner_d10', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e2', 'plan_full_body_beginner_d10', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e3', 'plan_full_body_beginner_d10', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e4', 'plan_full_body_beginner_d10', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e5', 'plan_full_body_beginner_d10', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e6', 'plan_full_body_beginner_d10', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d10_e7', 'plan_full_body_beginner_d10', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d11', 'plan_full_body_beginner', 11, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d12', 'plan_full_body_beginner', 12, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e0', 'plan_full_body_beginner_d12', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e1', 'plan_full_body_beginner_d12', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e2', 'plan_full_body_beginner_d12', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e3', 'plan_full_body_beginner_d12', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e4', 'plan_full_body_beginner_d12', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e5', 'plan_full_body_beginner_d12', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e6', 'plan_full_body_beginner_d12', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d12_e7', 'plan_full_body_beginner_d12', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d13', 'plan_full_body_beginner', 13, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d14', 'plan_full_body_beginner', 14, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e0', 'plan_full_body_beginner_d14', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e1', 'plan_full_body_beginner_d14', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e2', 'plan_full_body_beginner_d14', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e3', 'plan_full_body_beginner_d14', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e4', 'plan_full_body_beginner_d14', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e5', 'plan_full_body_beginner_d14', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e6', 'plan_full_body_beginner_d14', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d14_e7', 'plan_full_body_beginner_d14', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d15', 'plan_full_body_beginner', 15, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e0', 'plan_full_body_beginner_d15', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e1', 'plan_full_body_beginner_d15', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e2', 'plan_full_body_beginner_d15', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e3', 'plan_full_body_beginner_d15', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e4', 'plan_full_body_beginner_d15', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e5', 'plan_full_body_beginner_d15', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e6', 'plan_full_body_beginner_d15', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d15_e7', 'plan_full_body_beginner_d15', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d16', 'plan_full_body_beginner', 16, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d17', 'plan_full_body_beginner', 17, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e0', 'plan_full_body_beginner_d17', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e1', 'plan_full_body_beginner_d17', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e2', 'plan_full_body_beginner_d17', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e3', 'plan_full_body_beginner_d17', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e4', 'plan_full_body_beginner_d17', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e5', 'plan_full_body_beginner_d17', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e6', 'plan_full_body_beginner_d17', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d17_e7', 'plan_full_body_beginner_d17', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d18', 'plan_full_body_beginner', 18, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d19', 'plan_full_body_beginner', 19, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e0', 'plan_full_body_beginner_d19', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e1', 'plan_full_body_beginner_d19', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e2', 'plan_full_body_beginner_d19', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e3', 'plan_full_body_beginner_d19', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e4', 'plan_full_body_beginner_d19', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e5', 'plan_full_body_beginner_d19', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e6', 'plan_full_body_beginner_d19', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d19_e7', 'plan_full_body_beginner_d19', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d20', 'plan_full_body_beginner', 20, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d21', 'plan_full_body_beginner', 21, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e0', 'plan_full_body_beginner_d21', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e1', 'plan_full_body_beginner_d21', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e2', 'plan_full_body_beginner_d21', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e3', 'plan_full_body_beginner_d21', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e4', 'plan_full_body_beginner_d21', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e5', 'plan_full_body_beginner_d21', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e6', 'plan_full_body_beginner_d21', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d21_e7', 'plan_full_body_beginner_d21', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d22', 'plan_full_body_beginner', 22, 'Full Body Beginner', 0, 12)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e0', 'plan_full_body_beginner_d22', 'ex_jumping_jacks', 0, 3, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e1', 'plan_full_body_beginner_d22', 'ex_squat', 1, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e2', 'plan_full_body_beginner_d22', 'ex_push_up', 2, 3, 10, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e3', 'plan_full_body_beginner_d22', 'ex_reverse_lunge', 3, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e4', 'plan_full_body_beginner_d22', 'ex_glute_bridge', 4, 3, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e5', 'plan_full_body_beginner_d22', 'ex_plank', 5, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e6', 'plan_full_body_beginner_d22', 'ex_mountain_climbers', 6, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d22_e7', 'plan_full_body_beginner_d22', 'ex_superman', 7, 3, NULL, 20, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d23', 'plan_full_body_beginner', 23, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d24', 'plan_full_body_beginner', 24, 'Core Burner', 0, 10)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e0', 'plan_full_body_beginner_d24', 'ex_crunch', 0, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e1', 'plan_full_body_beginner_d24', 'ex_bicycle_crunch', 1, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e2', 'plan_full_body_beginner_d24', 'ex_leg_raise', 2, 3, 12, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e3', 'plan_full_body_beginner_d24', 'ex_russian_twist', 3, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e4', 'plan_full_body_beginner_d24', 'ex_plank', 4, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e5', 'plan_full_body_beginner_d24', 'ex_side_plank', 5, 3, NULL, 25, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e6', 'plan_full_body_beginner_d24', 'ex_flutter_kick', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d24_e7', 'plan_full_body_beginner_d24', 'ex_dead_bug', 7, 3, 12, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d25', 'plan_full_body_beginner', 25, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d26', 'plan_full_body_beginner', 26, 'Lower Body Focus', 0, 14)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e0', 'plan_full_body_beginner_d26', 'ex_squat', 0, 4, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e1', 'plan_full_body_beginner_d26', 'ex_reverse_lunge', 1, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e2', 'plan_full_body_beginner_d26', 'ex_glute_bridge', 2, 4, 15, NULL, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e3', 'plan_full_body_beginner_d26', 'ex_wall_sit', 3, 3, NULL, 40, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e4', 'plan_full_body_beginner_d26', 'ex_step_up', 4, 3, 12, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e5', 'plan_full_body_beginner_d26', 'ex_sumo_squat', 5, 3, 15, NULL, 30)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e6', 'plan_full_body_beginner_d26', 'ex_calf_raise', 6, 3, 20, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d26_e7', 'plan_full_body_beginner_d26', 'ex_donkey_kick', 7, 3, 15, NULL, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d27', 'plan_full_body_beginner', 27, 'Rest day', 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)
VALUES ('plan_full_body_beginner_d28', 'plan_full_body_beginner', 28, 'Cardio & Core', 0, 13)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e0', 'plan_full_body_beginner_d28', 'ex_high_knees', 0, 4, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e1', 'plan_full_body_beginner_d28', 'ex_jumping_jacks', 1, 4, NULL, 40, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e2', 'plan_full_body_beginner_d28', 'ex_burpee', 2, 3, 8, NULL, 35)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e3', 'plan_full_body_beginner_d28', 'ex_mountain_climbers', 3, 4, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e4', 'plan_full_body_beginner_d28', 'ex_skater_hops', 4, 3, NULL, 30, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e5', 'plan_full_body_beginner_d28', 'ex_plank', 5, 3, NULL, 40, 25)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e6', 'plan_full_body_beginner_d28', 'ex_bicycle_crunch', 6, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)
VALUES ('plan_full_body_beginner_d28_e7', 'plan_full_body_beginner_d28', 'ex_butt_kicks', 7, 3, NULL, 30, 20)
ON CONFLICT(id) DO NOTHING;
