/**
 * Emits the reference-data migration from the catalogues the app already
 * ships.
 *
 * Reference data is the one kind of row production is allowed to start with:
 * the exercise catalogue and the achievement definitions are facts about the
 * app, not facts about any person. Everything else in `src/data/seed.ts` is a
 * fixture and never reaches a server.
 *
 * Generated rather than hand-written so the migration cannot drift from the
 * catalogue the UI reads. Run with:
 *
 *   npx tsx --tsconfig tsconfig.app.json scripts/build-reference-migration.ts
 */
import { writeFileSync } from 'node:fs'
import { EXERCISES } from '../src/data/library'
import { ACHIEVEMENTS } from '../src/data/achievements'

/** SQL string literal. Single quotes double, nothing else is interpolated. */
const q = (value: string | undefined | null): string =>
  value === undefined || value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`

const lines: string[] = [
  '-- 0004 — reference data.',
  '--',
  '-- Generated by scripts/build-reference-migration.ts from the same',
  '-- catalogues the interface reads, so the two cannot drift. Re-run the',
  '-- script rather than editing this file by hand.',
  '--',
  '-- Nothing here names a person. This is the only data production starts',
  '-- with; every other row must be created by a real user through the real',
  '-- application.',
  '',
  'PRAGMA foreign_keys = ON;',
  '',
  '-- --- Exercise catalogue --------------------------------------------------',
  '',
]

for (const exercise of EXERCISES) {
  lines.push(
    'INSERT INTO exercises (id, name, muscle_groups, equipment, met, cue) VALUES (' +
      [
        q(exercise.id),
        q(exercise.name),
        q(JSON.stringify(exercise.muscleGroups ?? [])),
        q(exercise.equipment),
        String(exercise.met ?? 8),
        q(exercise.cue),
      ].join(', ') +
      ');',
  )
}

lines.push('', '-- --- Achievement definitions ---------------------------------------------', '')

for (const achievement of ACHIEVEMENTS) {
  lines.push(
    'INSERT INTO achievement_definitions (key, title, description, icon, group_name, criteria, tier) VALUES (' +
      [
        q(achievement.key),
        q(achievement.title),
        q(achievement.description),
        q(achievement.icon),
        q(achievement.group),
        q(achievement.criteria),
        String(achievement.tier ?? 1),
      ].join(', ') +
      ');',
  )
}

lines.push('')
writeFileSync('migrations/0004_reference_data.sql', lines.join('\n'), 'utf8')
console.log(
  `Wrote migrations/0004_reference_data.sql — ${EXERCISES.length} exercises, ${ACHIEVEMENTS.length} achievement definitions.`,
)
