/**
 * Writes the plan catalogue out as SQL.
 *
 * The programmes are reference data — they describe exercise, not people — and
 * they already exist in `src/data/library.ts`, generated from a handful of
 * templates. Copying them into a migration by hand would be transcription with
 * a hundred chances to differ from what the app builds; generating them means
 * the two cannot disagree.
 *
 * Nothing about a person is emitted. No owner, no enrollment, no progress.
 *
 *   npx tsx --tsconfig tsconfig.app.json scripts/build-plan-migration.ts
 */
import { writeFileSync } from 'node:fs'
import { PLAN_TEMPLATES, TEMPLATES, EXERCISES, slotForDay } from '../src/data/library'

/** SQLite string literal: single quotes doubled, nothing else interpolated. */
const q = (value: string | null | undefined) =>
  value === null || value === undefined ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`

const CREATED = '2026-01-01T00:00:00.000Z'
const lines: string[] = []

lines.push(`-- The plan catalogue.
--
-- Generated by scripts/build-plan-migration.ts from src/data/library.ts, so
-- the programmes on the server are the same programmes the application builds
-- rather than a transcription of them. Regenerate rather than edit.
--
-- Reference data: exercise templates and the days they fall on. It names
-- nobody, owns nothing, and records no progress. \`owner_id\` is null on every
-- row because these belong to the app, not to a person.
--
-- Safe to apply to an empty production database.
`)

const known = new Set(EXERCISES.map((exercise) => exercise.id))

for (const template of PLAN_TEMPLATES) {
  lines.push(
    `INSERT INTO plans (id, owner_id, name, description, total_days, level, focus, created_at)\n` +
      `VALUES (${q(template.id)}, NULL, ${q(template.name)}, ${q(template.description)}, ` +
      `${template.totalDays}, ${q(template.level)}, ${q(JSON.stringify(template.focus))}, ${q(CREATED)})\n` +
      `ON CONFLICT(id) DO NOTHING;`,
  )

  for (let dayNumber = 1; dayNumber <= template.totalDays; dayNumber += 1) {
    const slot = slotForDay(template, dayNumber)
    const planDayId = `${template.id}_d${dayNumber}`

    if (slot === 'rest') {
      lines.push(
        `INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)\n` +
          `VALUES (${q(planDayId)}, ${q(template.id)}, ${dayNumber}, 'Rest day', 1, 0)\n` +
          `ON CONFLICT(id) DO NOTHING;`,
      )
      continue
    }

    const workout = TEMPLATES[slot]
    lines.push(
      `INSERT INTO plan_days (id, plan_id, day_number, name, is_rest, estimated_minutes)\n` +
        `VALUES (${q(planDayId)}, ${q(template.id)}, ${dayNumber}, ${q(workout.name)}, 0, ${workout.estimatedMinutes})\n` +
        `ON CONFLICT(id) DO NOTHING;`,
    )

    workout.exercises.forEach((exercise, index) => {
      if (!known.has(exercise.exerciseId)) {
        throw new Error(`Plan references an exercise the catalogue does not have: ${exercise.exerciseId}`)
      }
      lines.push(
        `INSERT INTO plan_exercises (id, plan_day_id, exercise_id, position, sets, reps, duration_sec, rest_sec)\n` +
          `VALUES (${q(`${planDayId}_e${index}`)}, ${q(planDayId)}, ${q(exercise.exerciseId)}, ${index}, ` +
          `${exercise.sets ?? 'NULL'}, ${exercise.reps ?? 'NULL'}, ${exercise.durationSec ?? 'NULL'}, ` +
          `${exercise.restSec ?? 'NULL'})\n` +
          `ON CONFLICT(id) DO NOTHING;`,
      )
    })
  }
}

const path = 'migrations/0012_plan_catalogue.sql'
writeFileSync(path, `${lines.join('\n\n')}\n`, 'utf8')
console.log(`Wrote ${path} — ${PLAN_TEMPLATES.length} plans, ${lines.length - 1} statements.`)
